import { QuizQuestion, QuizDifficulty, QuizTopic } from '../types/backend-types';

export const defaultQuizQuestions: QuizQuestion[] = [
  // Budgeting Questions (15)
  {
    id: 'q1',
    question: 'What percentage of your income should you save according to the 50/30/20 rule?',
    options: ['10%', '20%', '30%', '50%'],
    correctAnswer: '20%',
    explanation: 'The 50/30/20 rule suggests allocating 50% to needs, 30% to wants, and 20% to savings and debt repayment.',
    realLifeTip: 'Start with 10% if 20% seems difficult, then gradually increase your savings rate as you optimize expenses.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q2',
    question: 'What is a budget?',
    options: ['A spending limit', 'A plan for income and expenses', 'A savings goal', 'A debt payment'],
    correctAnswer: 'A plan for income and expenses',
    explanation: 'A budget is a financial plan that tracks income and allocates it to expenses, savings, and debt repayment.',
    realLifeTip: 'Review and adjust your budget monthly to stay on track with your financial goals.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q3',
    question: 'What is net worth?',
    options: ['Total income', 'Assets minus liabilities', 'Salary after taxes', 'Investment returns'],
    correctAnswer: 'Assets minus liabilities',
    explanation: 'Net worth is calculated by subtracting your total liabilities (debts) from your total assets (what you own).',
    realLifeTip: 'Track your net worth quarterly to monitor your overall financial progress.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q4',
    question: 'What is the purpose of a financial goal?',
    options: ['To spend more', 'To provide direction and motivation', 'To increase debt', 'To avoid budgeting'],
    correctAnswer: 'To provide direction and motivation',
    explanation: 'Financial goals give you a clear target to work toward and help prioritize spending and saving decisions.',
    realLifeTip: 'Set SMART goals: Specific, Measurable, Achievable, Relevant, and Time-bound.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q5',
    question: 'What is the envelope budgeting method?',
    options: ['Digital budgeting', 'Allocating cash to categories in envelopes', 'Investment strategy', 'Debt payment plan'],
    correctAnswer: 'Allocating cash to categories in envelopes',
    explanation: 'The envelope method involves dividing cash into envelopes for different spending categories to control expenses.',
    realLifeTip: 'Use digital envelope budgeting apps if carrying cash isn\'t practical for you.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q6',
    question: 'What is zero-based budgeting?',
    options: ['Spending nothing', 'Allocating every dollar to a category', 'Having zero savings', 'Eliminating all debt'],
    correctAnswer: 'Allocating every dollar to a category',
    explanation: 'Zero-based budgeting means assigning every dollar of income to expenses, savings, or debt until you reach zero.',
    realLifeTip: 'This method ensures intentional spending and helps identify wasteful expenses.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q7',
    question: 'How often should you review your budget?',
    options: ['Once a year', 'Monthly', 'Never', 'Only when problems arise'],
    correctAnswer: 'Monthly',
    explanation: 'Monthly budget reviews help you track progress, adjust for changes, and stay aligned with your financial goals.',
    realLifeTip: 'Set a recurring calendar reminder for budget review day each month.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q8',
    question: 'What are fixed expenses?',
    options: ['Expenses that vary monthly', 'Expenses that stay the same each month', 'One-time purchases', 'Emergency costs'],
    correctAnswer: 'Expenses that stay the same each month',
    explanation: 'Fixed expenses are regular, predictable costs like rent, insurance, and loan payments that don\'t change monthly.',
    realLifeTip: 'Automate fixed expense payments to ensure they\'re always paid on time.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q9',
    question: 'What are variable expenses?',
    options: ['Expenses that stay the same', 'Expenses that change monthly', 'Annual expenses', 'Investment costs'],
    correctAnswer: 'Expenses that change monthly',
    explanation: 'Variable expenses fluctuate each month, like groceries, entertainment, and utilities.',
    realLifeTip: 'Track variable expenses closely to identify opportunities for savings.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q10',
    question: 'What is a sinking fund?',
    options: ['Emergency fund', 'Savings for planned future expenses', 'Investment account', 'Debt payment'],
    correctAnswer: 'Savings for planned future expenses',
    explanation: 'A sinking fund is money set aside regularly for planned future expenses like vacations, car repairs, or annual insurance.',
    realLifeTip: 'Create separate sinking funds for different goals to avoid dipping into emergency savings.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q11',
    question: 'What is the difference between gross and net income?',
    options: ['No difference', 'Gross is before taxes, net is after', 'Net is higher', 'Gross includes bonuses only'],
    correctAnswer: 'Gross is before taxes, net is after',
    explanation: 'Gross income is your total earnings before deductions, while net income is what you take home after taxes and deductions.',
    realLifeTip: 'Budget based on net income to avoid overspending and ensure you can meet all obligations.',
    topic: QuizTopic.salaryManagement,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q12',
    question: 'What is lifestyle inflation?',
    options: ['Rising prices', 'Increasing spending as income rises', 'Investment growth', 'Debt accumulation'],
    correctAnswer: 'Increasing spending as income rises',
    explanation: 'Lifestyle inflation occurs when spending increases proportionally or more than income increases, limiting savings growth.',
    realLifeTip: 'When you get a raise, increase savings first before upgrading your lifestyle.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q13',
    question: 'What is the pay yourself first principle?',
    options: ['Paying bills first', 'Saving before spending', 'Buying what you want first', 'Paying off debt first'],
    correctAnswer: 'Saving before spending',
    explanation: 'Pay yourself first means automatically saving a portion of income before allocating money to expenses.',
    realLifeTip: 'Set up automatic transfers to savings on payday to make this effortless.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q14',
    question: 'What is discretionary spending?',
    options: ['Essential expenses', 'Non-essential wants', 'Debt payments', 'Savings'],
    correctAnswer: 'Non-essential wants',
    explanation: 'Discretionary spending covers non-essential items like entertainment, dining out, and hobbies.',
    realLifeTip: 'This is the easiest category to cut when you need to increase savings or reduce debt.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q15',
    question: 'What is the 24-hour rule in budgeting?',
    options: ['Pay bills within 24 hours', 'Wait 24 hours before non-essential purchases', 'Budget every 24 hours', 'Save 24% of income'],
    correctAnswer: 'Wait 24 hours before non-essential purchases',
    explanation: 'The 24-hour rule suggests waiting a day before making non-essential purchases to reduce impulse buying.',
    realLifeTip: 'This simple delay often reveals that you don\'t actually need the item.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.easy,
  },

  // Saving Questions (15)
  {
    id: 'q16',
    question: 'How many months of expenses should an emergency fund ideally cover?',
    options: ['1-2 months', '3-6 months', '12 months', '24 months'],
    correctAnswer: '3-6 months',
    explanation: 'Financial experts recommend having 3-6 months of essential living expenses saved in an easily accessible emergency fund.',
    realLifeTip: 'Start with a goal of one month\'s expenses, then gradually build up to 3-6 months over time.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q17',
    question: 'What is the primary purpose of insurance?',
    options: ['Investment growth', 'Risk transfer', 'Tax savings', 'Wealth accumulation'],
    correctAnswer: 'Risk transfer',
    explanation: 'Insurance transfers financial risk from you to the insurance company in exchange for premium payments.',
    realLifeTip: 'Prioritize health and term life insurance before considering investment-linked policies.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q18',
    question: 'What is liquidity in finance?',
    options: ['Investment returns', 'How quickly assets convert to cash', 'Debt amount', 'Interest rate'],
    correctAnswer: 'How quickly assets convert to cash',
    explanation: 'Liquidity refers to how easily and quickly an asset can be converted to cash without significant loss of value.',
    realLifeTip: 'Keep emergency funds in highly liquid accounts like savings accounts for quick access.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q19',
    question: 'What is a high-yield savings account?',
    options: ['A checking account', 'A savings account with higher interest rates', 'An investment account', 'A retirement account'],
    correctAnswer: 'A savings account with higher interest rates',
    explanation: 'High-yield savings accounts offer higher interest rates than traditional savings accounts, helping your money grow faster.',
    realLifeTip: 'Compare rates from online banks, which often offer better rates than traditional banks.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q20',
    question: 'What is the difference between saving and investing?',
    options: ['No difference', 'Saving preserves money, investing grows it', 'Investing is safer', 'Saving has higher returns'],
    correctAnswer: 'Saving preserves money, investing grows it',
    explanation: 'Savings protect money with minimal risk for short-term needs, while investing aims to grow wealth over time with some risk.',
    realLifeTip: 'Use savings for short-term goals and emergency funds; use investing for long-term wealth building.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q21',
    question: 'What is compound interest?',
    options: ['Interest on principal only', 'Interest on interest', 'Fixed interest rate', 'Simple interest'],
    correctAnswer: 'Interest on interest',
    explanation: 'Compound interest is interest calculated on both the initial principal and accumulated interest from previous periods.',
    realLifeTip: 'Start investing early to maximize the power of compound interest over time.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q22',
    question: 'What is the rule of 72?',
    options: ['Retirement age', 'Estimating investment doubling time', 'Credit score calculation', 'Debt payment formula'],
    correctAnswer: 'Estimating investment doubling time',
    explanation: 'The rule of 72 estimates how long it takes for an investment to double by dividing 72 by the annual return rate.',
    realLifeTip: 'At 8% annual return, your money doubles in about 9 years (72 ÷ 8 = 9).',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q23',
    question: 'What is a certificate of deposit (CD)?',
    options: ['A credit card', 'A time deposit with fixed interest', 'A stock', 'A loan'],
    correctAnswer: 'A time deposit with fixed interest',
    explanation: 'A CD is a savings product that holds a fixed amount of money for a fixed period at a guaranteed interest rate.',
    realLifeTip: 'CDs are good for money you won\'t need for a specific period, offering higher rates than regular savings.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q24',
    question: 'What is automatic savings?',
    options: ['Manual transfers', 'Scheduled automatic transfers to savings', 'Spending less', 'Earning more'],
    correctAnswer: 'Scheduled automatic transfers to savings',
    explanation: 'Automatic savings involves setting up recurring transfers from checking to savings accounts without manual intervention.',
    realLifeTip: 'Automate savings on payday to ensure you save before you have a chance to spend.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q25',
    question: 'What is the time value of money?',
    options: ['Money loses value over time', 'Money today is worth more than same amount in future', 'Time equals money', 'Money has no time value'],
    correctAnswer: 'Money today is worth more than same amount in future',
    explanation: 'The time value of money principle states that money available now is worth more than the same amount in the future due to its earning potential.',
    realLifeTip: 'Invest early to maximize the time value of money through compound growth.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q26',
    question: 'What is a money market account?',
    options: ['A checking account', 'A savings account with check-writing privileges', 'A stock account', 'A retirement account'],
    correctAnswer: 'A savings account with check-writing privileges',
    explanation: 'Money market accounts combine features of savings and checking accounts, offering higher interest with limited check-writing.',
    realLifeTip: 'Good for emergency funds that need to be accessible but should earn more than regular savings.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q27',
    question: 'What is the best first step in building wealth?',
    options: ['Investing in stocks', 'Building an emergency fund', 'Buying a house', 'Starting a business'],
    correctAnswer: 'Building an emergency fund',
    explanation: 'An emergency fund provides financial security and prevents debt when unexpected expenses arise, forming the foundation of wealth building.',
    realLifeTip: 'Aim for $1,000 first, then build to 3-6 months of expenses before aggressive investing.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q28',
    question: 'What is a financial emergency?',
    options: ['Vacation expense', 'Unexpected necessary expense', 'Planned purchase', 'Investment opportunity'],
    correctAnswer: 'Unexpected necessary expense',
    explanation: 'A financial emergency is an unexpected expense that requires immediate attention, like medical bills or car repairs.',
    realLifeTip: 'Build an emergency fund to handle unexpected expenses without going into debt.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q29',
    question: 'Where should you keep your emergency fund?',
    options: ['Stocks', 'High-yield savings account', 'Real estate', 'Cryptocurrency'],
    correctAnswer: 'High-yield savings account',
    explanation: 'Emergency funds should be in liquid, low-risk accounts like high-yield savings for quick access without market risk.',
    realLifeTip: 'Avoid investing emergency funds in volatile assets that could lose value when you need them.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q30',
    question: 'What is the micro-saving strategy?',
    options: ['Saving large amounts', 'Saving small amounts regularly', 'Saving only once a year', 'Not saving at all'],
    correctAnswer: 'Saving small amounts regularly',
    explanation: 'Micro-saving involves setting aside small amounts frequently, like rounding up purchases or saving spare change.',
    realLifeTip: 'Apps that round up purchases to the nearest dollar and save the difference make micro-saving effortless.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },

  // Investing Questions (20)
  {
    id: 'q31',
    question: 'What is a stock?',
    options: ['A loan to a company', 'Ownership share in a company', 'A savings bond', 'A type of insurance'],
    correctAnswer: 'Ownership share in a company',
    explanation: 'A stock represents partial ownership in a company, giving you a claim on its assets and earnings.',
    realLifeTip: 'Research companies thoroughly before buying stocks and consider starting with index funds for diversification.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q32',
    question: 'What is a bond?',
    options: ['Company ownership', 'A loan to an entity', 'A savings account', 'A stock type'],
    correctAnswer: 'A loan to an entity',
    explanation: 'A bond is a debt security where you lend money to a government or corporation in exchange for periodic interest payments.',
    realLifeTip: 'Bonds are generally less risky than stocks and provide steady income, good for conservative portfolios.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q33',
    question: 'What is a mutual fund?',
    options: ['A single stock', 'A pooled investment vehicle', 'A savings account', 'A type of loan'],
    correctAnswer: 'A pooled investment vehicle',
    explanation: 'Mutual funds pool money from many investors to purchase a diversified portfolio of stocks, bonds, or other securities.',
    realLifeTip: 'Mutual funds offer instant diversification and professional management for beginner investors.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q34',
    question: 'What is an index fund?',
    options: ['A single stock', 'A fund tracking a market index', 'A savings account', 'A type of bond'],
    correctAnswer: 'A fund tracking a market index',
    explanation: 'An index fund is a type of mutual fund or ETF designed to track the performance of a specific market index.',
    realLifeTip: 'Index funds offer low-cost diversification and historically outperform most actively managed funds.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q35',
    question: 'What is diversification in investing?',
    options: ['Buying one stock', 'Spreading investments across different assets', 'Investing only in bonds', 'Day trading'],
    correctAnswer: 'Spreading investments across different assets',
    explanation: 'Diversification reduces risk by spreading investments across various asset classes, sectors, and geographies.',
    realLifeTip: 'Don\'t put all your eggs in one basket - diversify across stocks, bonds, and other assets.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q36',
    question: 'What is dollar-cost averaging?',
    options: ['Buying stocks at lowest price', 'Investing fixed amounts regularly', 'Selling at peak', 'Day trading strategy'],
    correctAnswer: 'Investing fixed amounts regularly',
    explanation: 'Dollar-cost averaging involves investing a fixed amount at regular intervals, regardless of market conditions.',
    realLifeTip: 'Set up automatic monthly investments to benefit from dollar-cost averaging without timing the market.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q37',
    question: 'What is a 401(k)?',
    options: ['A type of loan', 'An employer-sponsored retirement plan', 'A savings account', 'A credit score'],
    correctAnswer: 'An employer-sponsored retirement plan',
    explanation: 'A 401(k) is a retirement savings plan sponsored by employers, often with matching contributions and tax advantages.',
    realLifeTip: 'Contribute enough to get the full employer match - it\'s free money for your retirement.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q38',
    question: 'What is a Roth IRA?',
    options: ['A checking account', 'A retirement account with tax-free withdrawals', 'A type of loan', 'A credit card'],
    correctAnswer: 'A retirement account with tax-free withdrawals',
    explanation: 'A Roth IRA is a retirement account where contributions are taxed upfront, but qualified withdrawals in retirement are tax-free.',
    realLifeTip: 'Consider a Roth IRA if you expect to be in a higher tax bracket in retirement.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q39',
    question: 'What is inflation?',
    options: ['Decrease in prices', 'Increase in general price levels', 'Stock market growth', 'Interest rate'],
    correctAnswer: 'Increase in general price levels',
    explanation: 'Inflation is the rate at which the general level of prices for goods and services rises, eroding purchasing power.',
    realLifeTip: 'Invest in assets that historically outpace inflation, like stocks and real estate.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q40',
    question: 'What is passive income?',
    options: ['Salary from job', 'Income earned with minimal ongoing effort', 'One-time payment', 'Borrowed money'],
    correctAnswer: 'Income earned with minimal ongoing effort',
    explanation: 'Passive income is money earned from investments, rental properties, or businesses that require little active involvement.',
    realLifeTip: 'Build passive income streams through dividend stocks, rental properties, or online businesses.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q41',
    question: 'What is a financial advisor?',
    options: ['Bank teller', 'Professional providing financial guidance', 'Tax collector', 'Insurance agent'],
    correctAnswer: 'Professional providing financial guidance',
    explanation: 'A financial advisor is a professional who provides guidance on investments, retirement planning, and overall financial strategy.',
    realLifeTip: 'Look for fee-only fiduciary advisors who are legally required to act in your best interest.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q42',
    question: 'What is asset allocation?',
    options: ['Buying one asset', 'Distributing investments across asset classes', 'Selling stocks', 'Saving money'],
    correctAnswer: 'Distributing investments across asset classes',
    explanation: 'Asset allocation is the strategy of dividing investments among different asset categories like stocks, bonds, and cash.',
    realLifeTip: 'Adjust your asset allocation based on age, risk tolerance, and financial goals.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q43',
    question: 'What is an ETF (Exchange-Traded Fund)?',
    options: ['A single stock', 'A fund that trades like a stock', 'A savings account', 'A type of bond'],
    correctAnswer: 'A fund that trades like a stock',
    explanation: 'An ETF is a collection of securities that tracks an index and trades on an exchange like a stock.',
    realLifeTip: 'ETFs combine the diversification of mutual funds with the flexibility of stock trading.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q44',
    question: 'What is a dividend?',
    options: ['Stock price increase', 'Company profit distribution to shareholders', 'Interest payment', 'Tax refund'],
    correctAnswer: 'Company profit distribution to shareholders',
    explanation: 'A dividend is a portion of a company\'s earnings distributed to shareholders, usually quarterly.',
    realLifeTip: 'Dividend-paying stocks provide regular income and can be reinvested for compound growth.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q45',
    question: 'What is market capitalization?',
    options: ['Company revenue', 'Total value of company shares', 'Profit margin', 'Debt amount'],
    correctAnswer: 'Total value of company shares',
    explanation: 'Market cap is the total value of a company\'s outstanding shares, calculated by multiplying share price by number of shares.',
    realLifeTip: 'Companies are categorized as large-cap, mid-cap, or small-cap based on market capitalization.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q46',
    question: 'What is a bull market?',
    options: ['Declining market', 'Rising market', 'Stable market', 'Volatile market'],
    correctAnswer: 'Rising market',
    explanation: 'A bull market is a period of rising stock prices, typically defined as a 20% increase from recent lows.',
    realLifeTip: 'Bull markets reward long-term investors who stay invested through market cycles.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q47',
    question: 'What is a bear market?',
    options: ['Rising market', 'Declining market', 'Stable market', 'New market'],
    correctAnswer: 'Declining market',
    explanation: 'A bear market is a period of falling stock prices, typically defined as a 20% decline from recent highs.',
    realLifeTip: 'Bear markets are opportunities to buy quality investments at lower prices for long-term gains.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q48',
    question: 'What is a SIP (Systematic Investment Plan)?',
    options: ['One-time investment', 'Regular fixed investments', 'Savings account', 'Insurance plan'],
    correctAnswer: 'Regular fixed investments',
    explanation: 'A SIP allows you to invest a fixed amount regularly in mutual funds, leveraging rupee-cost averaging.',
    realLifeTip: 'SIPs are ideal for beginners, removing the need to time the market and building discipline.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q49',
    question: 'What is portfolio rebalancing?',
    options: ['Selling all investments', 'Adjusting asset allocation back to target', 'Buying more stocks', 'Closing accounts'],
    correctAnswer: 'Adjusting asset allocation back to target',
    explanation: 'Rebalancing involves buying or selling assets to maintain your desired asset allocation as market values change.',
    realLifeTip: 'Rebalance annually or when allocations drift more than 5% from targets.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q50',
    question: 'What is the expense ratio in mutual funds?',
    options: ['Fund performance', 'Annual fee as percentage of assets', 'Minimum investment', 'Tax rate'],
    correctAnswer: 'Annual fee as percentage of assets',
    explanation: 'The expense ratio is the annual fee charged by mutual funds, expressed as a percentage of assets under management.',
    realLifeTip: 'Lower expense ratios mean more of your money stays invested and compounds over time.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },

  // Stock Market Questions (15)
  {
    id: 'q51',
    question: 'What is the stock market?',
    options: ['A grocery store', 'A marketplace for buying and selling stocks', 'A bank', 'A government office'],
    correctAnswer: 'A marketplace for buying and selling stocks',
    explanation: 'The stock market is a platform where investors buy and sell shares of publicly traded companies.',
    realLifeTip: 'Start learning about the stock market through paper trading before investing real money.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q52',
    question: 'What is an IPO (Initial Public Offering)?',
    options: ['Stock split', 'First public sale of company stock', 'Dividend payment', 'Stock buyback'],
    correctAnswer: 'First public sale of company stock',
    explanation: 'An IPO is when a private company offers its shares to the public for the first time.',
    realLifeTip: 'IPOs can be volatile; research thoroughly and consider waiting for price stabilization.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q53',
    question: 'What is a stock exchange?',
    options: ['A bank', 'A platform where stocks are traded', 'A government agency', 'A type of stock'],
    correctAnswer: 'A platform where stocks are traded',
    explanation: 'A stock exchange is an organized marketplace where securities are bought and sold, like NYSE or NASDAQ.',
    realLifeTip: 'Major exchanges have listing requirements that provide some quality assurance for investors.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q54',
    question: 'What is a stock ticker symbol?',
    options: ['Stock price', 'Unique company identifier', 'Trading volume', 'Market index'],
    correctAnswer: 'Unique company identifier',
    explanation: 'A ticker symbol is a unique series of letters assigned to a security for trading purposes.',
    realLifeTip: 'Ticker symbols make it easy to quickly identify and trade specific stocks.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q55',
    question: 'What is a market order?',
    options: ['Order at specific price', 'Order executed immediately at current price', 'Cancelled order', 'Pending order'],
    correctAnswer: 'Order executed immediately at current price',
    explanation: 'A market order buys or sells a stock immediately at the best available current price.',
    realLifeTip: 'Use market orders for liquid stocks when you want immediate execution.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q56',
    question: 'What is a limit order?',
    options: ['Immediate execution', 'Order at specified price or better', 'Cancelled order', 'Market order'],
    correctAnswer: 'Order at specified price or better',
    explanation: 'A limit order sets the maximum price you\'ll pay to buy or minimum price you\'ll accept to sell.',
    realLifeTip: 'Limit orders give you price control but may not execute if the price isn\'t reached.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q57',
    question: 'What is trading volume?',
    options: ['Stock price', 'Number of shares traded', 'Company size', 'Profit amount'],
    correctAnswer: 'Number of shares traded',
    explanation: 'Trading volume is the total number of shares traded during a specific period.',
    realLifeTip: 'High volume indicates strong interest and liquidity, making it easier to buy or sell.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q58',
    question: 'What is a stock split?',
    options: ['Selling half your shares', 'Dividing existing shares into multiple shares', 'Merging companies', 'Dividend payment'],
    correctAnswer: 'Dividing existing shares into multiple shares',
    explanation: 'A stock split increases the number of shares while proportionally decreasing the price per share.',
    realLifeTip: 'Stock splits don\'t change your investment value, just the number of shares you own.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q59',
    question: 'What is a blue-chip stock?',
    options: ['New startup stock', 'Large, established, financially sound company', 'Penny stock', 'Foreign stock'],
    correctAnswer: 'Large, established, financially sound company',
    explanation: 'Blue-chip stocks are shares of large, reputable companies with a history of reliable performance.',
    realLifeTip: 'Blue-chip stocks are generally less volatile and good for conservative portfolios.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q60',
    question: 'What is a penny stock?',
    options: ['Expensive stock', 'Low-priced, speculative stock', 'Dividend stock', 'Index fund'],
    correctAnswer: 'Low-priced, speculative stock',
    explanation: 'Penny stocks are low-priced shares of small companies, typically trading under $5 per share.',
    realLifeTip: 'Penny stocks are highly risky and speculative; avoid them until you\'re an experienced investor.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q61',
    question: 'What is the P/E ratio (Price-to-Earnings)?',
    options: ['Profit margin', 'Stock price divided by earnings per share', 'Dividend yield', 'Market cap'],
    correctAnswer: 'Stock price divided by earnings per share',
    explanation: 'The P/E ratio measures a company\'s stock price relative to its earnings, indicating valuation.',
    realLifeTip: 'Compare P/E ratios within the same industry to identify potentially overvalued or undervalued stocks.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q62',
    question: 'What is a stock broker?',
    options: ['Company CEO', 'Intermediary facilitating stock trades', 'Government regulator', 'Stock analyst'],
    correctAnswer: 'Intermediary facilitating stock trades',
    explanation: 'A stock broker is a licensed professional or firm that executes buy and sell orders for investors.',
    realLifeTip: 'Modern online brokers offer low-cost trading with user-friendly platforms for beginners.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q63',
    question: 'What is day trading?',
    options: ['Long-term investing', 'Buying and selling within the same day', 'Monthly trading', 'Annual trading'],
    correctAnswer: 'Buying and selling within the same day',
    explanation: 'Day trading involves buying and selling securities within the same trading day to profit from short-term price movements.',
    realLifeTip: 'Day trading is extremely risky and not recommended for beginners; most day traders lose money.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q64',
    question: 'What is a market index?',
    options: ['Single stock', 'Measure of market segment performance', 'Trading platform', 'Investment account'],
    correctAnswer: 'Measure of market segment performance',
    explanation: 'A market index tracks the performance of a group of stocks representing a market segment, like the S&P 500.',
    realLifeTip: 'Indexes provide benchmarks to compare your portfolio performance against the overall market.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q65',
    question: 'What is volatility in the stock market?',
    options: ['Trading volume', 'Price fluctuation magnitude', 'Company size', 'Dividend amount'],
    correctAnswer: 'Price fluctuation magnitude',
    explanation: 'Volatility measures how much and how quickly stock prices change over time.',
    realLifeTip: 'High volatility means higher risk but also potential for higher returns; match volatility to your risk tolerance.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },

  // Mutual Funds & SIP Questions (15)
  {
    id: 'q66',
    question: 'What is the main advantage of mutual funds?',
    options: ['Guaranteed returns', 'Professional management and diversification', 'No fees', 'Tax-free returns'],
    correctAnswer: 'Professional management and diversification',
    explanation: 'Mutual funds offer professional management and instant diversification across multiple securities.',
    realLifeTip: 'Mutual funds are ideal for beginners who want diversification without picking individual stocks.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q67',
    question: 'What is an equity mutual fund?',
    options: ['Bond fund', 'Fund investing primarily in stocks', 'Money market fund', 'Real estate fund'],
    correctAnswer: 'Fund investing primarily in stocks',
    explanation: 'Equity mutual funds invest primarily in stocks, offering higher growth potential with higher risk.',
    realLifeTip: 'Equity funds are suitable for long-term goals (5+ years) due to market volatility.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q68',
    question: 'What is a debt mutual fund?',
    options: ['Stock fund', 'Fund investing in fixed-income securities', 'Real estate fund', 'Commodity fund'],
    correctAnswer: 'Fund investing in fixed-income securities',
    explanation: 'Debt mutual funds invest in bonds, government securities, and other fixed-income instruments.',
    realLifeTip: 'Debt funds are less volatile than equity funds and suitable for short to medium-term goals.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q69',
    question: 'What is NAV (Net Asset Value)?',
    options: ['Number of shares', 'Per-share value of mutual fund', 'Annual return', 'Management fee'],
    correctAnswer: 'Per-share value of mutual fund',
    explanation: 'NAV is the per-share value of a mutual fund, calculated by dividing total assets minus liabilities by number of shares.',
    realLifeTip: 'NAV changes daily based on the value of the fund\'s underlying securities.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q70',
    question: 'What is the minimum SIP amount typically?',
    options: ['₹10,000', '₹500-₹1,000', '₹50,000', '₹100'],
    correctAnswer: '₹500-₹1,000',
    explanation: 'Most mutual funds allow SIPs starting from ₹500 to ₹1,000, making investing accessible to everyone.',
    realLifeTip: 'Start with what you can afford and gradually increase your SIP amount as income grows.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q71',
    question: 'What is the benefit of SIP over lump sum investment?',
    options: ['Higher guaranteed returns', 'Rupee-cost averaging and discipline', 'No market risk', 'Tax-free returns'],
    correctAnswer: 'Rupee-cost averaging and discipline',
    explanation: 'SIPs average out purchase costs over time and build investment discipline through regular contributions.',
    realLifeTip: 'SIPs remove the stress of market timing and are perfect for salaried individuals.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q72',
    question: 'What is a balanced mutual fund?',
    options: ['Only stocks', 'Mix of stocks and bonds', 'Only bonds', 'Only cash'],
    correctAnswer: 'Mix of stocks and bonds',
    explanation: 'Balanced funds invest in both equity and debt instruments, balancing growth potential with stability.',
    realLifeTip: 'Balanced funds are good for moderate risk tolerance and medium-term goals.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q73',
    question: 'What is an ELSS (Equity Linked Savings Scheme)?',
    options: ['Debt fund', 'Tax-saving equity mutual fund', 'Fixed deposit', 'Insurance plan'],
    correctAnswer: 'Tax-saving equity mutual fund',
    explanation: 'ELSS is an equity mutual fund that offers tax deductions under Section 80C with a 3-year lock-in period.',
    realLifeTip: 'ELSS has the shortest lock-in among tax-saving investments and potential for higher returns.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q74',
    question: 'What is a liquid fund?',
    options: ['Stock fund', 'Short-term debt fund', 'Real estate fund', 'Gold fund'],
    correctAnswer: 'Short-term debt fund',
    explanation: 'Liquid funds invest in very short-term debt instruments, offering high liquidity with minimal risk.',
    realLifeTip: 'Liquid funds are ideal for parking emergency funds or money needed within a few months.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q75',
    question: 'What is the lock-in period for ELSS?',
    options: ['No lock-in', '3 years', '5 years', '10 years'],
    correctAnswer: '3 years',
    explanation: 'ELSS has a mandatory 3-year lock-in period, the shortest among tax-saving investment options.',
    realLifeTip: 'The lock-in ensures you stay invested long enough to benefit from equity market growth.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q76',
    question: 'What is a growth option in mutual funds?',
    options: ['Regular dividend payout', 'Reinvested returns for compounding', 'Fixed returns', 'Guaranteed growth'],
    correctAnswer: 'Reinvested returns for compounding',
    explanation: 'Growth option reinvests all returns back into the fund, maximizing compounding benefits.',
    realLifeTip: 'Choose growth option for long-term wealth building; dividend option for regular income needs.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q77',
    question: 'What is a dividend option in mutual funds?',
    options: ['Reinvested returns', 'Periodic profit distribution', 'Guaranteed returns', 'Tax-free returns'],
    correctAnswer: 'Periodic profit distribution',
    explanation: 'Dividend option distributes profits periodically to investors instead of reinvesting them.',
    realLifeTip: 'Dividends are now taxable in investors\' hands; growth option is more tax-efficient for wealth building.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q78',
    question: 'What is a sectoral mutual fund?',
    options: ['Diversified fund', 'Fund focused on specific industry', 'Debt fund', 'Balanced fund'],
    correctAnswer: 'Fund focused on specific industry',
    explanation: 'Sectoral funds invest in companies from a specific sector like technology, pharma, or banking.',
    realLifeTip: 'Sectoral funds are riskier due to lack of diversification; suitable only for experienced investors.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q79',
    question: 'What is a large-cap mutual fund?',
    options: ['Small company fund', 'Fund investing in large, established companies', 'Startup fund', 'Debt fund'],
    correctAnswer: 'Fund investing in large, established companies',
    explanation: 'Large-cap funds invest in the largest companies by market capitalization, offering stability.',
    realLifeTip: 'Large-cap funds are less volatile and suitable for conservative equity investors.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q80',
    question: 'What is a mid-cap mutual fund?',
    options: ['Large company fund', 'Fund investing in medium-sized companies', 'Debt fund', 'Money market fund'],
    correctAnswer: 'Fund investing in medium-sized companies',
    explanation: 'Mid-cap funds invest in medium-sized companies with higher growth potential and moderate risk.',
    realLifeTip: 'Mid-cap funds balance growth potential with reasonable stability for long-term investors.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },

  // Emergency Funds & Credit Questions (10)
  {
    id: 'q81',
    question: 'What is a credit score primarily used for?',
    options: ['Tax calculation', 'Loan approval', 'Salary negotiation', 'Investment returns'],
    correctAnswer: 'Loan approval',
    explanation: 'Credit scores help lenders assess your creditworthiness and determine loan approval and interest rates.',
    realLifeTip: 'Pay bills on time and keep credit utilization below 30% to maintain a good credit score.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q82',
    question: 'What is the difference between a debit card and a credit card?',
    options: ['No difference', 'Debit uses your money, credit borrows money', 'Credit is safer', 'Debit has higher fees'],
    correctAnswer: 'Debit uses your money, credit borrows money',
    explanation: 'Debit cards withdraw money directly from your bank account, while credit cards let you borrow money up to a limit.',
    realLifeTip: 'Use credit cards responsibly and pay the full balance monthly to avoid interest charges.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q83',
    question: 'What is a credit utilization ratio?',
    options: ['Total debt', 'Credit used divided by credit available', 'Number of credit cards', 'Credit score'],
    correctAnswer: 'Credit used divided by credit available',
    explanation: 'Credit utilization is the percentage of available credit you\'re using, calculated by dividing credit used by total credit limit.',
    realLifeTip: 'Keep credit utilization below 30% to maintain a healthy credit score.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q84',
    question: 'What is a balance transfer?',
    options: ['Moving money between accounts', 'Moving credit card debt to another card', 'Investment rebalancing', 'Salary deposit'],
    correctAnswer: 'Moving credit card debt to another card',
    explanation: 'A balance transfer moves debt from one credit card to another, often to take advantage of lower interest rates.',
    realLifeTip: 'Use balance transfers strategically with 0% intro APR offers, but pay off before the promotional period ends.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q85',
    question: 'What factors affect your credit score?',
    options: ['Only income', 'Payment history, utilization, credit age, inquiries', 'Only debt amount', 'Only number of cards'],
    correctAnswer: 'Payment history, utilization, credit age, inquiries',
    explanation: 'Credit scores consider payment history (35%), utilization (30%), credit age (15%), new credit (10%), and credit mix (10%).',
    realLifeTip: 'Payment history is the biggest factor; never miss payments to maintain a good score.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q86',
    question: 'What is a good credit score range?',
    options: ['300-500', '700-850', '100-300', '1000-1500'],
    correctAnswer: '700-850',
    explanation: 'Credit scores range from 300-850, with 700+ considered good and 750+ considered excellent.',
    realLifeTip: 'Aim for 750+ to qualify for the best interest rates on loans and credit cards.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q87',
    question: 'What is the minimum payment on a credit card?',
    options: ['Full balance', 'Small percentage of balance', 'Interest only', 'No payment required'],
    correctAnswer: 'Small percentage of balance',
    explanation: 'The minimum payment is typically 2-5% of the outstanding balance, but paying only this accrues high interest.',
    realLifeTip: 'Always pay the full balance to avoid interest charges; minimum payments lead to debt traps.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q88',
    question: 'What is a credit inquiry?',
    options: ['Checking your own score', 'Lender checking your credit report', 'Paying off debt', 'Opening a bank account'],
    correctAnswer: 'Lender checking your credit report',
    explanation: 'A credit inquiry occurs when a lender checks your credit report, which can temporarily lower your score.',
    realLifeTip: 'Limit credit applications to avoid multiple hard inquiries that can hurt your score.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q89',
    question: 'What is the grace period on a credit card?',
    options: ['Time to pay without interest', 'Late payment penalty period', 'Card expiration time', 'Reward redemption period'],
    correctAnswer: 'Time to pay without interest',
    explanation: 'The grace period is typically 21-25 days from statement date to payment due date, during which no interest accrues on new purchases.',
    realLifeTip: 'Pay your full balance before the grace period ends to avoid interest charges.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q90',
    question: 'What is a secured credit card?',
    options: ['Card with no fees', 'Card requiring a security deposit', 'Card with rewards', 'Card with no limit'],
    correctAnswer: 'Card requiring a security deposit',
    explanation: 'A secured credit card requires a cash deposit as collateral, making it easier to get with poor or no credit history.',
    realLifeTip: 'Secured cards are great for building or rebuilding credit; use responsibly and graduate to unsecured cards.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.medium,
  },

  // Debt & Loans Questions (10)
  {
    id: 'q91',
    question: 'What does APR stand for in finance?',
    options: ['Annual Payment Rate', 'Annual Percentage Rate', 'Average Payment Return', 'Annual Principal Rate'],
    correctAnswer: 'Annual Percentage Rate',
    explanation: 'APR represents the yearly cost of borrowing money, including interest and fees.',
    realLifeTip: 'Always compare APRs when shopping for loans or credit cards to find the best deal.',
    topic: QuizTopic.loans,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q92',
    question: 'What is the debt-to-income ratio?',
    options: ['Total debt divided by monthly income', 'Monthly debt payments divided by gross monthly income', 'Annual debt divided by savings', 'Credit card debt only'],
    correctAnswer: 'Monthly debt payments divided by gross monthly income',
    explanation: 'DTI ratio compares your monthly debt payments to your gross monthly income, helping lenders assess your ability to repay.',
    realLifeTip: 'Keep your DTI below 36% for better loan approval chances and financial health.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q93',
    question: 'What is the best way to pay off multiple debts?',
    options: ['Pay minimum on all', 'Avalanche or snowball method', 'Ignore smallest debts', 'Take new loans'],
    correctAnswer: 'Avalanche or snowball method',
    explanation: 'Avalanche method targets highest interest debts first; snowball method pays smallest debts first for psychological wins.',
    realLifeTip: 'Choose the method that keeps you motivated - avalanche saves more money, snowball provides quick wins.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q94',
    question: 'What is a personal loan?',
    options: ['Secured loan', 'Unsecured loan for personal use', 'Business loan', 'Mortgage'],
    correctAnswer: 'Unsecured loan for personal use',
    explanation: 'A personal loan is an unsecured loan that can be used for various personal expenses without collateral.',
    realLifeTip: 'Personal loans have higher interest than secured loans; use them only when necessary and compare rates.',
    topic: QuizTopic.loans,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q95',
    question: 'What is an EMI (Equated Monthly Installment)?',
    options: ['One-time payment', 'Fixed monthly loan payment', 'Interest-only payment', 'Variable payment'],
    correctAnswer: 'Fixed monthly loan payment',
    explanation: 'EMI is a fixed monthly payment that includes both principal and interest, used to repay loans.',
    realLifeTip: 'Calculate EMI before taking a loan to ensure it fits comfortably in your budget.',
    topic: QuizTopic.loans,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q96',
    question: 'What is the debt avalanche method?',
    options: ['Paying smallest debt first', 'Paying highest interest debt first', 'Paying newest debt first', 'Paying random debts'],
    correctAnswer: 'Paying highest interest debt first',
    explanation: 'The debt avalanche method prioritizes paying off debts with the highest interest rates first to minimize total interest paid.',
    realLifeTip: 'Avalanche method saves the most money but requires discipline; track progress to stay motivated.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q97',
    question: 'What is the debt snowball method?',
    options: ['Paying highest interest first', 'Paying smallest balance first', 'Paying largest balance first', 'Paying random debts'],
    correctAnswer: 'Paying smallest balance first',
    explanation: 'The debt snowball method focuses on paying off the smallest debt first for quick psychological wins and motivation.',
    realLifeTip: 'Snowball method builds momentum and confidence; great if you need motivation to tackle debt.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q98',
    question: 'What is a secured loan?',
    options: ['Loan without collateral', 'Loan backed by collateral', 'Loan with no interest', 'Loan with no repayment'],
    correctAnswer: 'Loan backed by collateral',
    explanation: 'A secured loan requires collateral (like a house or car) that the lender can seize if you default.',
    realLifeTip: 'Secured loans have lower interest rates but risk losing your collateral if you can\'t repay.',
    topic: QuizTopic.loans,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q99',
    question: 'What is an unsecured loan?',
    options: ['Loan with collateral', 'Loan without collateral', 'Loan with no interest', 'Loan with no approval'],
    correctAnswer: 'Loan without collateral',
    explanation: 'An unsecured loan doesn\'t require collateral but typically has higher interest rates due to increased lender risk.',
    realLifeTip: 'Personal loans and credit cards are unsecured; maintain good credit for better rates.',
    topic: QuizTopic.loans,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q100',
    question: 'What is loan prepayment?',
    options: ['Missing a payment', 'Paying off loan early', 'Refinancing', 'Defaulting'],
    correctAnswer: 'Paying off loan early',
    explanation: 'Loan prepayment means paying off part or all of a loan before the scheduled due date, reducing total interest paid.',
    realLifeTip: 'Check for prepayment penalties before paying off loans early; many lenders charge fees.',
    topic: QuizTopic.loans,
    difficulty: QuizDifficulty.medium,
  },
];
