import { QuizQuestion, QuizDifficulty, QuizTopic } from '../types/backend-types';

export const defaultQuizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'What percentage of your income should you save according to the 50/30/20 rule?',
    options: ['10%', '20%', '30%', '50%'],
    correctAnswer: '20%',
    explanation: 'The 50/30/20 rule suggests allocating 50% to needs, 30% to wants, and 20% to savings and debt repayment.',
    realLifeTip: 'Start with 10% if 20% seems difficult, then gradually increase your savings rate as you optimize expenses.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q2',
    question: 'How many months of expenses should an emergency fund ideally cover?',
    options: ['1-2 months', '3-6 months', '12 months', '24 months'],
    correctAnswer: '3-6 months',
    explanation: 'Financial experts recommend having 3-6 months of essential living expenses saved in an easily accessible emergency fund.',
    realLifeTip: 'Start with a goal of one month\'s expenses, then gradually build up to 3-6 months over time.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q3',
    question: 'What is compound interest?',
    options: ['Interest on principal only', 'Interest on interest', 'Fixed interest rate', 'Simple interest'],
    correctAnswer: 'Interest on interest',
    explanation: 'Compound interest is interest calculated on both the initial principal and accumulated interest from previous periods.',
    realLifeTip: 'Start investing early to maximize the power of compound interest over time.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q4',
    question: 'What is a credit score primarily used for?',
    options: ['Tax calculation', 'Loan approval', 'Salary negotiation', 'Investment returns'],
    correctAnswer: 'Loan approval',
    explanation: 'Credit scores help lenders assess your creditworthiness and determine loan approval and interest rates.',
    realLifeTip: 'Pay bills on time and keep credit utilization below 30% to maintain a good credit score.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q5',
    question: 'What does APR stand for in finance?',
    options: ['Annual Payment Rate', 'Annual Percentage Rate', 'Average Payment Return', 'Annual Principal Rate'],
    correctAnswer: 'Annual Percentage Rate',
    explanation: 'APR represents the yearly cost of borrowing money, including interest and fees.',
    realLifeTip: 'Always compare APRs when shopping for loans or credit cards to find the best deal.',
    topic: QuizTopic.loans,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q6',
    question: 'What is diversification in investing?',
    options: ['Buying one stock', 'Spreading investments across different assets', 'Investing only in bonds', 'Day trading'],
    correctAnswer: 'Spreading investments across different assets',
    explanation: 'Diversification reduces risk by spreading investments across various asset classes, sectors, and geographies.',
    realLifeTip: 'Don\'t put all your eggs in one basket - diversify across stocks, bonds, and other assets.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q7',
    question: 'What is the debt-to-income ratio?',
    options: ['Total debt divided by monthly income', 'Monthly debt payments divided by gross monthly income', 'Annual debt divided by savings', 'Credit card debt only'],
    correctAnswer: 'Monthly debt payments divided by gross monthly income',
    explanation: 'DTI ratio compares your monthly debt payments to your gross monthly income, helping lenders assess your ability to repay.',
    realLifeTip: 'Keep your DTI below 36% for better loan approval chances and financial health.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q8',
    question: 'What is inflation?',
    options: ['Decrease in prices', 'Increase in general price levels', 'Stock market growth', 'Interest rate'],
    correctAnswer: 'Increase in general price levels',
    explanation: 'Inflation is the rate at which the general level of prices for goods and services rises, eroding purchasing power.',
    realLifeTip: 'Invest in assets that historically outpace inflation, like stocks and real estate.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q9',
    question: 'What is a mutual fund?',
    options: ['A single stock', 'A pooled investment vehicle', 'A savings account', 'A type of loan'],
    correctAnswer: 'A pooled investment vehicle',
    explanation: 'Mutual funds pool money from many investors to purchase a diversified portfolio of stocks, bonds, or other securities.',
    realLifeTip: 'Mutual funds offer instant diversification and professional management for beginner investors.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q10',
    question: 'What is the primary purpose of insurance?',
    options: ['Investment growth', 'Risk transfer', 'Tax savings', 'Wealth accumulation'],
    correctAnswer: 'Risk transfer',
    explanation: 'Insurance transfers financial risk from you to the insurance company in exchange for premium payments.',
    realLifeTip: 'Prioritize health and term life insurance before considering investment-linked policies.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q11',
    question: 'What is a budget?',
    options: ['A spending limit', 'A plan for income and expenses', 'A savings goal', 'A debt payment'],
    correctAnswer: 'A plan for income and expenses',
    explanation: 'A budget is a financial plan that tracks income and allocates it to expenses, savings, and debt repayment.',
    realLifeTip: 'Review and adjust your budget monthly to stay on track with your financial goals.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q12',
    question: 'What is the difference between a debit card and a credit card?',
    options: ['No difference', 'Debit uses your money, credit borrows money', 'Credit is safer', 'Debit has higher fees'],
    correctAnswer: 'Debit uses your money, credit borrows money',
    explanation: 'Debit cards withdraw money directly from your bank account, while credit cards let you borrow money up to a limit.',
    realLifeTip: 'Use credit cards responsibly and pay the full balance monthly to avoid interest charges.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q13',
    question: 'What is net worth?',
    options: ['Total income', 'Assets minus liabilities', 'Salary after taxes', 'Investment returns'],
    correctAnswer: 'Assets minus liabilities',
    explanation: 'Net worth is calculated by subtracting your total liabilities (debts) from your total assets (what you own).',
    realLifeTip: 'Track your net worth quarterly to monitor your overall financial progress.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q14',
    question: 'What is dollar-cost averaging?',
    options: ['Buying stocks at lowest price', 'Investing fixed amounts regularly', 'Selling at peak', 'Day trading strategy'],
    correctAnswer: 'Investing fixed amounts regularly',
    explanation: 'Dollar-cost averaging involves investing a fixed amount at regular intervals, regardless of market conditions.',
    realLifeTip: 'Set up automatic monthly investments to benefit from dollar-cost averaging without timing the market.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q15',
    question: 'What is a 401(k)?',
    options: ['A type of loan', 'An employer-sponsored retirement plan', 'A savings account', 'A credit score'],
    correctAnswer: 'An employer-sponsored retirement plan',
    explanation: 'A 401(k) is a retirement savings plan sponsored by employers, often with matching contributions and tax advantages.',
    realLifeTip: 'Contribute enough to get the full employer match - it\'s free money for your retirement.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q16',
    question: 'What is the purpose of a financial goal?',
    options: ['To spend more', 'To provide direction and motivation', 'To increase debt', 'To avoid budgeting'],
    correctAnswer: 'To provide direction and motivation',
    explanation: 'Financial goals give you a clear target to work toward and help prioritize spending and saving decisions.',
    realLifeTip: 'Set SMART goals: Specific, Measurable, Achievable, Relevant, and Time-bound.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q17',
    question: 'What is liquidity in finance?',
    options: ['Investment returns', 'How quickly assets convert to cash', 'Debt amount', 'Interest rate'],
    correctAnswer: 'How quickly assets convert to cash',
    explanation: 'Liquidity refers to how easily and quickly an asset can be converted to cash without significant loss of value.',
    realLifeTip: 'Keep emergency funds in highly liquid accounts like savings accounts for quick access.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q18',
    question: 'What is a stock?',
    options: ['A loan to a company', 'Ownership share in a company', 'A savings bond', 'A type of insurance'],
    correctAnswer: 'Ownership share in a company',
    explanation: 'A stock represents partial ownership in a company, giving you a claim on its assets and earnings.',
    realLifeTip: 'Research companies thoroughly before buying stocks and consider starting with index funds for diversification.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q19',
    question: 'What is the best way to pay off multiple debts?',
    options: ['Pay minimum on all', 'Avalanche or snowball method', 'Ignore smallest debts', 'Take new loans'],
    correctAnswer: 'Avalanche or snowball method',
    explanation: 'Avalanche method targets highest interest debts first; snowball method pays smallest debts first for psychological wins.',
    realLifeTip: 'Choose the method that keeps you motivated - avalanche saves more money, snowball provides quick wins.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q20',
    question: 'What is a bond?',
    options: ['Company ownership', 'A loan to an entity', 'A savings account', 'A stock type'],
    correctAnswer: 'A loan to an entity',
    explanation: 'A bond is a debt security where you lend money to a government or corporation in exchange for periodic interest payments.',
    realLifeTip: 'Bonds are generally less risky than stocks and provide steady income, good for conservative portfolios.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q21',
    question: 'What is the time value of money?',
    options: ['Money loses value over time', 'Money today is worth more than same amount in future', 'Time equals money', 'Money has no time value'],
    correctAnswer: 'Money today is worth more than same amount in future',
    explanation: 'The time value of money principle states that money available now is worth more than the same amount in the future due to its earning potential.',
    realLifeTip: 'Invest early to maximize the time value of money through compound growth.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q22',
    question: 'What is a Roth IRA?',
    options: ['A checking account', 'A retirement account with tax-free withdrawals', 'A type of loan', 'A credit card'],
    correctAnswer: 'A retirement account with tax-free withdrawals',
    explanation: 'A Roth IRA is a retirement account where contributions are taxed upfront, but qualified withdrawals in retirement are tax-free.',
    realLifeTip: 'Consider a Roth IRA if you expect to be in a higher tax bracket in retirement.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q23',
    question: 'What is the envelope budgeting method?',
    options: ['Digital budgeting', 'Allocating cash to categories in envelopes', 'Investment strategy', 'Debt payment plan'],
    correctAnswer: 'Allocating cash to categories in envelopes',
    explanation: 'The envelope method involves dividing cash into envelopes for different spending categories to control expenses.',
    realLifeTip: 'Use digital envelope budgeting apps if carrying cash isn\'t practical for you.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q24',
    question: 'What is a credit utilization ratio?',
    options: ['Total debt', 'Credit used divided by credit available', 'Number of credit cards', 'Credit score'],
    correctAnswer: 'Credit used divided by credit available',
    explanation: 'Credit utilization is the percentage of available credit you\'re using, calculated by dividing credit used by total credit limit.',
    realLifeTip: 'Keep credit utilization below 30% to maintain a healthy credit score.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q25',
    question: 'What is passive income?',
    options: ['Salary from job', 'Income earned with minimal ongoing effort', 'One-time payment', 'Borrowed money'],
    correctAnswer: 'Income earned with minimal ongoing effort',
    explanation: 'Passive income is money earned from investments, rental properties, or businesses that require little active involvement.',
    realLifeTip: 'Build passive income streams through dividend stocks, rental properties, or online businesses.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q26',
    question: 'What is the difference between gross and net income?',
    options: ['No difference', 'Gross is before taxes, net is after', 'Net is higher', 'Gross includes bonuses only'],
    correctAnswer: 'Gross is before taxes, net is after',
    explanation: 'Gross income is your total earnings before deductions, while net income is what you take home after taxes and deductions.',
    realLifeTip: 'Budget based on net income to avoid overspending and ensure you can meet all obligations.',
    topic: QuizTopic.salaryManagement,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q27',
    question: 'What is an index fund?',
    options: ['A single stock', 'A fund tracking a market index', 'A savings account', 'A type of bond'],
    correctAnswer: 'A fund tracking a market index',
    explanation: 'An index fund is a type of mutual fund or ETF designed to track the performance of a specific market index.',
    realLifeTip: 'Index funds offer low-cost diversification and historically outperform most actively managed funds.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q28',
    question: 'What is a financial emergency?',
    options: ['Vacation expense', 'Unexpected necessary expense', 'Planned purchase', 'Investment opportunity'],
    correctAnswer: 'Unexpected necessary expense',
    explanation: 'A financial emergency is an unexpected expense that requires immediate attention, like medical bills or car repairs.',
    realLifeTip: 'Build an emergency fund to handle unexpected expenses without going into debt.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q29',
    question: 'What is the rule of 72?',
    options: ['Retirement age', 'Estimating investment doubling time', 'Credit score calculation', 'Debt payment formula'],
    correctAnswer: 'Estimating investment doubling time',
    explanation: 'The rule of 72 estimates how long it takes for an investment to double by dividing 72 by the annual return rate.',
    realLifeTip: 'At 8% annual return, your money doubles in about 9 years (72 ÷ 8 = 9).',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q30',
    question: 'What is lifestyle inflation?',
    options: ['Rising prices', 'Increasing spending as income rises', 'Investment growth', 'Debt accumulation'],
    correctAnswer: 'Increasing spending as income rises',
    explanation: 'Lifestyle inflation occurs when spending increases proportionally or more than income increases, limiting savings growth.',
    realLifeTip: 'When you get a raise, increase savings first before upgrading your lifestyle.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q31',
    question: 'What is a financial advisor?',
    options: ['Bank teller', 'Professional providing financial guidance', 'Tax collector', 'Insurance agent'],
    correctAnswer: 'Professional providing financial guidance',
    explanation: 'A financial advisor is a professional who provides guidance on investments, retirement planning, and overall financial strategy.',
    realLifeTip: 'Look for fee-only fiduciary advisors who are legally required to act in your best interest.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q32',
    question: 'What is a balance transfer?',
    options: ['Moving money between accounts', 'Moving credit card debt to another card', 'Investment rebalancing', 'Salary deposit'],
    correctAnswer: 'Moving credit card debt to another card',
    explanation: 'A balance transfer moves debt from one credit card to another, often to take advantage of lower interest rates.',
    realLifeTip: 'Use balance transfers strategically with 0% intro APR offers, but pay off before the promotional period ends.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q33',
    question: 'What is asset allocation?',
    options: ['Buying one asset', 'Distributing investments across asset classes', 'Selling stocks', 'Saving money'],
    correctAnswer: 'Distributing investments across asset classes',
    explanation: 'Asset allocation is the strategy of dividing investments among different asset categories like stocks, bonds, and cash.',
    realLifeTip: 'Adjust your asset allocation based on age, risk tolerance, and financial goals.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q34',
    question: 'What is a sinking fund?',
    options: ['Emergency fund', 'Savings for planned future expenses', 'Investment account', 'Debt payment'],
    correctAnswer: 'Savings for planned future expenses',
    explanation: 'A sinking fund is money set aside regularly for planned future expenses like vacations, car repairs, or annual insurance.',
    realLifeTip: 'Create separate sinking funds for different goals to avoid dipping into emergency savings.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q35',
    question: 'What is the debt snowball method?',
    options: ['Paying highest interest first', 'Paying smallest debt first', 'Ignoring debt', 'Consolidating all debt'],
    correctAnswer: 'Paying smallest debt first',
    explanation: 'The debt snowball method focuses on paying off the smallest debt first while making minimum payments on others for psychological wins.',
    realLifeTip: 'The snowball method provides motivation through quick wins, even if it costs slightly more in interest.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q36',
    question: 'What is a high-yield savings account?',
    options: ['Checking account', 'Savings account with higher interest rate', 'Investment account', 'Credit card'],
    correctAnswer: 'Savings account with higher interest rate',
    explanation: 'A high-yield savings account offers significantly higher interest rates than traditional savings accounts, often through online banks.',
    realLifeTip: 'Keep your emergency fund in a high-yield savings account to earn interest while maintaining liquidity.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q37',
    question: 'What is tax-loss harvesting?',
    options: ['Avoiding taxes', 'Selling losing investments to offset gains', 'Tax evasion', 'Retirement strategy'],
    correctAnswer: 'Selling losing investments to offset gains',
    explanation: 'Tax-loss harvesting involves selling investments at a loss to offset capital gains and reduce tax liability.',
    realLifeTip: 'Use tax-loss harvesting strategically at year-end, but be aware of wash-sale rules.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.hard,
  },
  {
    id: 'q38',
    question: 'What is a financial ratio?',
    options: ['Interest rate', 'Metric comparing financial data', 'Stock price', 'Savings amount'],
    correctAnswer: 'Metric comparing financial data',
    explanation: 'Financial ratios are metrics that compare different financial data points to assess financial health and performance.',
    realLifeTip: 'Track key personal ratios like savings rate, debt-to-income, and net worth growth.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q39',
    question: 'What is opportunity cost?',
    options: ['Investment fee', 'Value of next best alternative foregone', 'Interest rate', 'Tax amount'],
    correctAnswer: 'Value of next best alternative foregone',
    explanation: 'Opportunity cost is the potential benefit you miss out on when choosing one alternative over another.',
    realLifeTip: 'Consider opportunity costs when making financial decisions - what else could you do with that money?',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q40',
    question: 'What is a certificate of deposit (CD)?',
    options: ['Stock certificate', 'Time deposit with fixed interest', 'Credit card', 'Insurance policy'],
    correctAnswer: 'Time deposit with fixed interest',
    explanation: 'A CD is a savings product that holds a fixed amount of money for a fixed period at a guaranteed interest rate.',
    realLifeTip: 'Use CD laddering to maintain liquidity while earning higher rates on longer-term CDs.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q41',
    question: 'What is rebalancing in investing?',
    options: ['Selling all stocks', 'Adjusting portfolio to target allocation', 'Buying new stocks', 'Closing accounts'],
    correctAnswer: 'Adjusting portfolio to target allocation',
    explanation: 'Rebalancing involves periodically buying or selling assets to maintain your desired asset allocation.',
    realLifeTip: 'Rebalance your portfolio annually or when allocations drift more than 5% from targets.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q42',
    question: 'What is a budget deficit?',
    options: ['Spending more than income', 'Saving money', 'Investment loss', 'Debt payment'],
    correctAnswer: 'Spending more than income',
    explanation: 'A budget deficit occurs when expenses exceed income, requiring borrowing or drawing from savings.',
    realLifeTip: 'Track spending carefully and adjust expenses to avoid running a budget deficit.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q43',
    question: 'What is dollar-cost averaging best for?',
    options: ['Day trading', 'Long-term investing', 'Short-term gains', 'Market timing'],
    correctAnswer: 'Long-term investing',
    explanation: 'Dollar-cost averaging works best for long-term investing by reducing the impact of market volatility through regular investments.',
    realLifeTip: 'Set up automatic monthly investments to implement dollar-cost averaging effortlessly.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q44',
    question: 'What is a grace period on a credit card?',
    options: ['Late payment time', 'Interest-free period after purchase', 'Credit limit increase', 'Annual fee waiver'],
    correctAnswer: 'Interest-free period after purchase',
    explanation: 'A grace period is the time between purchase and payment due date when no interest is charged if you pay in full.',
    realLifeTip: 'Pay your credit card balance in full each month to take advantage of the grace period and avoid interest.',
    topic: QuizTopic.credit,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q45',
    question: 'What is the debt avalanche method?',
    options: ['Paying smallest debt first', 'Paying highest interest debt first', 'Ignoring debt', 'Minimum payments only'],
    correctAnswer: 'Paying highest interest debt first',
    explanation: 'The debt avalanche method prioritizes paying off debts with the highest interest rates first to minimize total interest paid.',
    realLifeTip: 'Use the avalanche method to save the most money on interest, even if progress feels slower initially.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q46',
    question: 'What is a financial statement?',
    options: ['Bank receipt', 'Document showing financial position', 'Credit report', 'Tax form'],
    correctAnswer: 'Document showing financial position',
    explanation: 'A financial statement is a formal record of financial activities, including income statements, balance sheets, and cash flow statements.',
    realLifeTip: 'Create personal financial statements quarterly to track your financial progress.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q47',
    question: 'What is a money market account?',
    options: ['Stock account', 'Savings account with check-writing', 'Credit card', 'Loan account'],
    correctAnswer: 'Savings account with check-writing',
    explanation: 'A money market account is a savings account that typically offers higher interest rates and limited check-writing privileges.',
    realLifeTip: 'Money market accounts are good for emergency funds, offering higher rates than regular savings with easy access.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q48',
    question: 'What is financial literacy?',
    options: ['Reading ability', 'Understanding financial concepts', 'Math skills', 'Investment returns'],
    correctAnswer: 'Understanding financial concepts',
    explanation: 'Financial literacy is the ability to understand and effectively use various financial skills, including budgeting, investing, and debt management.',
    realLifeTip: 'Continuously improve your financial literacy through books, courses, and practical experience.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q49',
    question: 'What is a bear market?',
    options: ['Rising market', 'Declining market by 20% or more', 'Stable market', 'New market'],
    correctAnswer: 'Declining market by 20% or more',
    explanation: 'A bear market is a period when stock prices fall 20% or more from recent highs, often accompanied by pessimism.',
    realLifeTip: 'Bear markets are opportunities to buy quality investments at lower prices if you have a long-term horizon.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q50',
    question: 'What is a bull market?',
    options: ['Declining market', 'Rising market', 'Volatile market', 'Closed market'],
    correctAnswer: 'Rising market',
    explanation: 'A bull market is a period of rising stock prices, typically characterized by investor optimism and economic growth.',
    realLifeTip: 'Don\'t get overconfident in bull markets - maintain your investment strategy and risk management.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q51',
    question: 'What is a financial cushion?',
    options: ['Investment portfolio', 'Emergency savings buffer', 'Credit limit', 'Retirement fund'],
    correctAnswer: 'Emergency savings buffer',
    explanation: 'A financial cushion is extra savings beyond your emergency fund that provides additional security and flexibility.',
    realLifeTip: 'Build a financial cushion of 6-12 months expenses for maximum peace of mind.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q52',
    question: 'What is compound growth?',
    options: ['Linear growth', 'Exponential growth from reinvested earnings', 'Negative growth', 'No growth'],
    correctAnswer: 'Exponential growth from reinvested earnings',
    explanation: 'Compound growth occurs when investment earnings are reinvested to generate additional earnings over time.',
    realLifeTip: 'Start investing early to maximize compound growth - time is your greatest asset.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q53',
    question: 'What is a spending trigger?',
    options: ['Budget category', 'Emotional or situational cause of spending', 'Payment method', 'Shopping list'],
    correctAnswer: 'Emotional or situational cause of spending',
    explanation: 'A spending trigger is an emotional state or situation that prompts unnecessary or impulsive spending.',
    realLifeTip: 'Identify your spending triggers and develop healthier coping mechanisms to avoid impulse purchases.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q54',
    question: 'What is the 24-hour rule for purchases?',
    options: ['Return policy', 'Waiting 24 hours before non-essential purchases', 'Payment deadline', 'Shipping time'],
    correctAnswer: 'Waiting 24 hours before non-essential purchases',
    explanation: 'The 24-hour rule suggests waiting a day before making non-essential purchases to avoid impulse buying.',
    realLifeTip: 'For larger purchases, extend the waiting period to a week or month to ensure it\'s truly needed.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q55',
    question: 'What is a financial milestone?',
    options: ['Monthly bill', 'Significant financial achievement', 'Investment loss', 'Debt increase'],
    correctAnswer: 'Significant financial achievement',
    explanation: 'A financial milestone is a significant achievement in your financial journey, like paying off debt or reaching a savings goal.',
    realLifeTip: 'Celebrate financial milestones to stay motivated, but avoid expensive celebrations that derail progress.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q56',
    question: 'What is automated saving?',
    options: ['Manual transfers', 'Automatic transfers to savings', 'Investment strategy', 'Debt payment'],
    correctAnswer: 'Automatic transfers to savings',
    explanation: 'Automated saving involves setting up automatic transfers from checking to savings accounts on a regular schedule.',
    realLifeTip: 'Automate savings on payday so you save before you have a chance to spend.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q57',
    question: 'What is a financial audit?',
    options: ['Tax investigation', 'Review of financial situation', 'Investment analysis', 'Credit check'],
    correctAnswer: 'Review of financial situation',
    explanation: 'A personal financial audit is a comprehensive review of your income, expenses, assets, debts, and overall financial health.',
    realLifeTip: 'Conduct a personal financial audit annually to identify areas for improvement.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q58',
    question: 'What is the latte factor?',
    options: ['Coffee addiction', 'Small daily expenses adding up', 'Investment strategy', 'Savings account'],
    correctAnswer: 'Small daily expenses adding up',
    explanation: 'The latte factor refers to small, regular expenses that seem insignificant but add up to substantial amounts over time.',
    realLifeTip: 'Track small daily expenses for a month to identify your "latte factors" and redirect that money to savings.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q59',
    question: 'What is a zero-based budget?',
    options: ['No budget', 'Every dollar assigned a purpose', 'Spending nothing', 'Debt-only budget'],
    correctAnswer: 'Every dollar assigned a purpose',
    explanation: 'A zero-based budget allocates every dollar of income to expenses, savings, or debt, leaving zero unassigned.',
    realLifeTip: 'Zero-based budgeting ensures intentional spending and maximizes savings by accounting for every dollar.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q60',
    question: 'What is financial independence?',
    options: ['Having a job', 'Having enough wealth to live without working', 'Owning a home', 'Being debt-free'],
    correctAnswer: 'Having enough wealth to live without working',
    explanation: 'Financial independence means having sufficient wealth and passive income to cover living expenses without needing to work.',
    realLifeTip: 'Calculate your FI number: annual expenses × 25 (based on the 4% withdrawal rule).',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q61',
    question: 'What is the 4% rule?',
    options: ['Interest rate', 'Safe retirement withdrawal rate', 'Savings rate', 'Investment return'],
    correctAnswer: 'Safe retirement withdrawal rate',
    explanation: 'The 4% rule suggests withdrawing 4% of your retirement portfolio annually to make it last 30+ years.',
    realLifeTip: 'The 4% rule is a guideline - adjust based on market conditions, expenses, and life expectancy.',
    topic: QuizTopic.investing,
    difficulty: QuizDifficulty.hard,
  },
  {
    id: 'q62',
    question: 'What is a side hustle?',
    options: ['Main job', 'Additional income source outside main job', 'Investment', 'Savings account'],
    correctAnswer: 'Additional income source outside main job',
    explanation: 'A side hustle is work or business done in addition to your main job to earn extra income.',
    realLifeTip: 'Start a side hustle aligned with your skills and interests to accelerate debt payoff or savings goals.',
    topic: QuizTopic.salaryManagement,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q63',
    question: 'What is lifestyle creep?',
    options: ['Inflation', 'Gradually increasing spending with income', 'Investment growth', 'Debt reduction'],
    correctAnswer: 'Gradually increasing spending with income',
    explanation: 'Lifestyle creep is the gradual increase in spending as income rises, preventing savings growth.',
    realLifeTip: 'Combat lifestyle creep by increasing savings rate proportionally with income increases.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q64',
    question: 'What is a financial buffer?',
    options: ['Investment account', 'Extra money for unexpected expenses', 'Credit card', 'Loan'],
    correctAnswer: 'Extra money for unexpected expenses',
    explanation: 'A financial buffer is extra money set aside to handle unexpected expenses or income fluctuations.',
    realLifeTip: 'Keep a buffer of 1-2 months expenses in checking to avoid overdrafts and fees.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q65',
    question: 'What is the pay yourself first principle?',
    options: ['Spending first', 'Saving before spending', 'Paying bills late', 'Investing last'],
    correctAnswer: 'Saving before spending',
    explanation: 'Pay yourself first means prioritizing savings by setting aside money for savings and investments before paying expenses.',
    realLifeTip: 'Automate savings transfers on payday to implement pay yourself first effortlessly.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q66',
    question: 'What is a financial goal timeline?',
    options: ['Budget period', 'Schedule for achieving financial goals', 'Investment duration', 'Loan term'],
    correctAnswer: 'Schedule for achieving financial goals',
    explanation: 'A financial goal timeline outlines when you plan to achieve specific financial objectives, from short to long-term.',
    realLifeTip: 'Categorize goals as short-term (1 year), medium-term (1-5 years), and long-term (5+ years).',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q67',
    question: 'What is impulse buying?',
    options: ['Planned purchase', 'Unplanned emotional purchase', 'Investment', 'Saving'],
    correctAnswer: 'Unplanned emotional purchase',
    explanation: 'Impulse buying is making unplanned purchases driven by emotion rather than need or careful consideration.',
    realLifeTip: 'Use a shopping list and the 24-hour rule to combat impulse buying.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q68',
    question: 'What is a financial safety net?',
    options: ['Investment portfolio', 'Emergency fund and insurance', 'Credit cards', 'Retirement account'],
    correctAnswer: 'Emergency fund and insurance',
    explanation: 'A financial safety net includes emergency savings and insurance coverage to protect against financial hardship.',
    realLifeTip: 'Build a complete safety net with emergency fund, health insurance, and term life insurance.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q69',
    question: 'What is the difference between saving and investing?',
    options: ['No difference', 'Saving is low-risk preservation, investing is growth-focused', 'Saving is riskier', 'Investing is safer'],
    correctAnswer: 'Saving is low-risk preservation, investing is growth-focused',
    explanation: 'Saving focuses on preserving money with minimal risk, while investing aims for growth by accepting more risk.',
    realLifeTip: 'Save for short-term goals and emergencies; invest for long-term goals like retirement.',
    topic: QuizTopic.saving,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q70',
    question: 'What is a spending plan?',
    options: ['Shopping list', 'Another term for budget', 'Investment strategy', 'Debt payment'],
    correctAnswer: 'Another term for budget',
    explanation: 'A spending plan is another term for a budget, outlining how you plan to allocate your income.',
    realLifeTip: 'Use "spending plan" instead of "budget" if the word budget feels restrictive.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q71',
    question: 'What is financial stress?',
    options: ['Investment loss', 'Anxiety about money matters', 'Market volatility', 'Tax season'],
    correctAnswer: 'Anxiety about money matters',
    explanation: 'Financial stress is the emotional tension and worry caused by money problems or financial uncertainty.',
    realLifeTip: 'Reduce financial stress by creating a budget, building emergency savings, and seeking help when needed.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q72',
    question: 'What is a financial priority?',
    options: ['Any expense', 'Most important financial goal or need', 'Investment type', 'Savings account'],
    correctAnswer: 'Most important financial goal or need',
    explanation: 'A financial priority is a goal or need that takes precedence over others in your financial planning.',
    realLifeTip: 'Rank your financial priorities and allocate resources accordingly, starting with essentials and emergency fund.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q73',
    question: 'What is the snowflake method?',
    options: ['Investment strategy', 'Applying small extra payments to debt', 'Savings technique', 'Budgeting system'],
    correctAnswer: 'Applying small extra payments to debt',
    explanation: 'The snowflake method involves making small, frequent extra payments toward debt whenever you find extra money.',
    realLifeTip: 'Combine snowflake payments with snowball or avalanche methods to accelerate debt payoff.',
    topic: QuizTopic.debts,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q74',
    question: 'What is a financial reset?',
    options: ['Bankruptcy', 'Fresh start with new financial habits', 'Investment loss', 'Loan refinance'],
    correctAnswer: 'Fresh start with new financial habits',
    explanation: 'A financial reset is a deliberate fresh start where you reassess and rebuild your financial habits and goals.',
    realLifeTip: 'Use life transitions as opportunities for financial resets to establish better money habits.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q75',
    question: 'What is a no-spend challenge?',
    options: ['Bankruptcy', 'Period of avoiding non-essential spending', 'Investment freeze', 'Savings withdrawal'],
    correctAnswer: 'Period of avoiding non-essential spending',
    explanation: 'A no-spend challenge is a set period where you commit to spending only on essentials to boost savings.',
    realLifeTip: 'Try a no-spend weekend or week to reset spending habits and redirect money to financial goals.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q76',
    question: 'What is financial wellness?',
    options: ['Being rich', 'Overall financial health and peace of mind', 'Investment returns', 'High income'],
    correctAnswer: 'Overall financial health and peace of mind',
    explanation: 'Financial wellness is a state of overall financial health where you feel secure, in control, and able to meet goals.',
    realLifeTip: 'Financial wellness includes managing debt, saving regularly, and having a plan for the future.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q77',
    question: 'What is a financial habit?',
    options: ['One-time action', 'Regular money-related behavior', 'Investment strategy', 'Savings goal'],
    correctAnswer: 'Regular money-related behavior',
    explanation: 'A financial habit is a regular, often automatic behavior related to how you earn, spend, save, or invest money.',
    realLifeTip: 'Build positive financial habits like tracking expenses daily and reviewing finances weekly.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q78',
    question: 'What is the purpose of tracking expenses?',
    options: ['Tax evasion', 'Understanding spending patterns', 'Increasing spending', 'Avoiding budgets'],
    correctAnswer: 'Understanding spending patterns',
    explanation: 'Tracking expenses helps you understand where your money goes, identify wasteful spending, and make informed financial decisions.',
    realLifeTip: 'Track every expense for at least one month to get an accurate picture of your spending habits.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q79',
    question: 'What is a financial accountability partner?',
    options: ['Bank teller', 'Someone who helps you stay on track financially', 'Financial advisor', 'Tax preparer'],
    correctAnswer: 'Someone who helps you stay on track financially',
    explanation: 'A financial accountability partner is someone who supports and encourages you to stick to your financial goals.',
    realLifeTip: 'Choose a trusted friend or family member as an accountability partner for regular financial check-ins.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q80',
    question: 'What is the difference between needs and wants?',
    options: ['No difference', 'Needs are essential, wants are desires', 'Wants are more important', 'Needs cost more'],
    correctAnswer: 'Needs are essential, wants are desires',
    explanation: 'Needs are essential for survival and basic functioning, while wants are things you desire but can live without.',
    realLifeTip: 'Before purchasing, ask yourself: "Is this a need or a want?" to make better spending decisions.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q81',
    question: 'What is a financial cushion goal?',
    options: ['Retirement target', 'Extra savings beyond emergency fund', 'Investment return', 'Debt payoff'],
    correctAnswer: 'Extra savings beyond emergency fund',
    explanation: 'A financial cushion goal is building savings beyond your emergency fund for additional security and opportunities.',
    realLifeTip: 'After building a 6-month emergency fund, work toward a 12-month cushion for maximum flexibility.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q82',
    question: 'What is mindful spending?',
    options: ['Spending everything', 'Intentional, value-aligned spending', 'Impulse buying', 'No spending'],
    correctAnswer: 'Intentional, value-aligned spending',
    explanation: 'Mindful spending means making intentional purchases that align with your values and bring genuine satisfaction.',
    realLifeTip: 'Before buying, ask: "Does this purchase align with my values and goals?"',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q83',
    question: 'What is a financial vision board?',
    options: ['Investment chart', 'Visual representation of financial goals', 'Budget spreadsheet', 'Credit report'],
    correctAnswer: 'Visual representation of financial goals',
    explanation: 'A financial vision board is a visual collage of images and words representing your financial goals and dreams.',
    realLifeTip: 'Create a vision board with images of your goals to stay motivated and focused on your financial journey.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q84',
    question: 'What is the purpose of a budget review?',
    options: ['Punishment', 'Assessing and adjusting financial plan', 'Increasing spending', 'Avoiding goals'],
    correctAnswer: 'Assessing and adjusting financial plan',
    explanation: 'A budget review involves regularly assessing your budget\'s effectiveness and making necessary adjustments.',
    realLifeTip: 'Review your budget monthly to ensure it still aligns with your current situation and goals.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q85',
    question: 'What is a financial setback?',
    options: ['Investment gain', 'Unexpected event harming finances', 'Planned expense', 'Savings increase'],
    correctAnswer: 'Unexpected event harming finances',
    explanation: 'A financial setback is an unexpected event or circumstance that negatively impacts your financial situation.',
    realLifeTip: 'Build resilience through emergency savings and insurance to recover quickly from financial setbacks.',
    topic: QuizTopic.emergencyFunds,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q86',
    question: 'What is the purpose of financial education?',
    options: ['Entertainment', 'Building knowledge for better decisions', 'Avoiding money', 'Increasing debt'],
    correctAnswer: 'Building knowledge for better decisions',
    explanation: 'Financial education provides knowledge and skills to make informed decisions about money management and wealth building.',
    realLifeTip: 'Commit to ongoing financial education through books, courses, podcasts, and practical experience.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q87',
    question: 'What is a spending freeze?',
    options: ['Account closure', 'Temporary halt on non-essential spending', 'Investment pause', 'Savings withdrawal'],
    correctAnswer: 'Temporary halt on non-essential spending',
    explanation: 'A spending freeze is a temporary period where you stop all non-essential spending to boost savings or pay down debt.',
    realLifeTip: 'Try a 30-day spending freeze on a specific category to break bad habits and save extra money.',
    topic: QuizTopic.spending,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q88',
    question: 'What is financial confidence?',
    options: ['Arrogance', 'Trust in your financial knowledge and decisions', 'High income', 'Investment success'],
    correctAnswer: 'Trust in your financial knowledge and decisions',
    explanation: 'Financial confidence is the self-assurance that comes from understanding money and making informed financial decisions.',
    realLifeTip: 'Build financial confidence through education, small wins, and consistent positive money habits.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q89',
    question: 'What is a financial boundary?',
    options: ['Credit limit', 'Limit on money-related behaviors', 'Investment restriction', 'Savings cap'],
    correctAnswer: 'Limit on money-related behaviors',
    explanation: 'A financial boundary is a limit you set on money-related behaviors to protect your financial health and goals.',
    realLifeTip: 'Set boundaries like "I don\'t lend money to friends" or "I don\'t shop when emotional."',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q90',
    question: 'What is the purpose of a financial journal?',
    options: ['Tax records', 'Tracking thoughts and behaviors about money', 'Investment log', 'Expense tracking'],
    correctAnswer: 'Tracking thoughts and behaviors about money',
    explanation: 'A financial journal helps you track your thoughts, emotions, and behaviors related to money to identify patterns.',
    realLifeTip: 'Journal about money decisions and emotions to understand your financial psychology better.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q91',
    question: 'What is a financial win?',
    options: ['Lottery jackpot', 'Any positive financial achievement', 'Investment gain only', 'Salary increase'],
    correctAnswer: 'Any positive financial achievement',
    explanation: 'A financial win is any positive achievement in your financial journey, no matter how small.',
    realLifeTip: 'Celebrate small wins like saving $100 or paying off a small debt to stay motivated.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q92',
    question: 'What is the purpose of a financial check-in?',
    options: ['Bank visit', 'Regular review of financial progress', 'Credit check', 'Tax filing'],
    correctAnswer: 'Regular review of financial progress',
    explanation: 'A financial check-in is a regular review of your financial situation, progress toward goals, and necessary adjustments.',
    realLifeTip: 'Schedule weekly or monthly financial check-ins to stay on track and catch issues early.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q93',
    question: 'What is financial procrastination?',
    options: ['Quick decisions', 'Delaying important financial tasks', 'Automated savings', 'Investment strategy'],
    correctAnswer: 'Delaying important financial tasks',
    explanation: 'Financial procrastination is putting off important money-related tasks like budgeting, investing, or debt repayment.',
    realLifeTip: 'Break financial tasks into small steps and schedule specific times to complete them.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q94',
    question: 'What is a financial comfort zone?',
    options: ['Luxury lifestyle', 'Familiar money habits and behaviors', 'High income', 'No debt'],
    correctAnswer: 'Familiar money habits and behaviors',
    explanation: 'A financial comfort zone is the range of money behaviors and situations that feel familiar and safe, even if not optimal.',
    realLifeTip: 'Growth requires stepping outside your financial comfort zone - start with small, manageable changes.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
  {
    id: 'q95',
    question: 'What is the purpose of financial goals?',
    options: ['Restriction', 'Providing direction and motivation', 'Punishment', 'Avoiding spending'],
    correctAnswer: 'Providing direction and motivation',
    explanation: 'Financial goals provide clear direction for your money decisions and motivation to stick with your financial plan.',
    realLifeTip: 'Write down specific, measurable goals with deadlines to increase your likelihood of achieving them.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q96',
    question: 'What is a financial mistake?',
    options: ['Any spending', 'Poor money decision with negative consequences', 'Investment loss', 'Budget variance'],
    correctAnswer: 'Poor money decision with negative consequences',
    explanation: 'A financial mistake is a poor money decision that leads to negative consequences, but also provides learning opportunities.',
    realLifeTip: 'Learn from financial mistakes rather than dwelling on them - they\'re valuable lessons for future decisions.',
    topic: QuizTopic.mistakes,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q97',
    question: 'What is financial awareness?',
    options: ['Ignorance', 'Understanding your financial situation', 'High income', 'Investment knowledge'],
    correctAnswer: 'Understanding your financial situation',
    explanation: 'Financial awareness is having a clear understanding of your current financial situation, including income, expenses, assets, and debts.',
    realLifeTip: 'Increase financial awareness by tracking all accounts and reviewing your complete financial picture monthly.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q98',
    question: 'What is the purpose of a financial plan?',
    options: ['Restriction', 'Roadmap for achieving financial goals', 'Tax avoidance', 'Spending guide only'],
    correctAnswer: 'Roadmap for achieving financial goals',
    explanation: 'A financial plan is a comprehensive roadmap outlining how you\'ll achieve your financial goals over time.',
    realLifeTip: 'Create a written financial plan covering short, medium, and long-term goals with specific action steps.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q99',
    question: 'What is financial empowerment?',
    options: ['High income', 'Control and confidence over finances', 'Investment success', 'Debt freedom'],
    correctAnswer: 'Control and confidence over finances',
    explanation: 'Financial empowerment is having the knowledge, skills, and confidence to take control of your financial future.',
    realLifeTip: 'Empower yourself financially through education, action, and building positive money habits.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.easy,
  },
  {
    id: 'q100',
    question: 'What is the most important factor in financial success?',
    options: ['High income', 'Consistent positive habits', 'Luck', 'Investment timing'],
    correctAnswer: 'Consistent positive habits',
    explanation: 'Financial success comes primarily from consistent positive habits like saving regularly, living below your means, and investing for the long term.',
    realLifeTip: 'Focus on building sustainable financial habits rather than seeking quick wins or perfect timing.',
    topic: QuizTopic.budgeting,
    difficulty: QuizDifficulty.medium,
  },
];
